aboutus_contactus/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about_us, name='aboutus_page'),
    path('rules/', views.rules, name='rules_page'),
    path('contact/', views.contact_us, name='contact_us_page'),
    path('send-contact/', views.ContactView.as_view(), name='contact_page'),
    path('user-panel/', views.UserPanelView.as_view(), name='user_panel_page'),
    path('my-tickets/', views.UserContactListView.as_view(), name='user_tickets_page'),
    path('my-address/', views.UserAddressView.as_view(), name='user_address_page'),
    path('my-orders/', views.UserOrdersView.as_view(), name='user_orders_page'),
    path('ajax/orders/<str:status>/', views.UserOrdersAjaxView.as_view(), name='ajax-orders'),
    path('ajax/user-counts/', views.get_user_counts, name='get_user_counts')
]

bache_poosh/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home.views import robots_txt
from django.contrib.sitemaps.views import sitemap
from home.site_map import StaticViewSitemap, ProductSitemap, ArticleSitemap, ArticleCategorySitemap
sitemaps = {
    'products': ProductSitemap,
    'categories': StaticViewSitemap,
    'articles': ArticleSitemap,
    'articles_cat': ArticleCategorySitemap,
}
urlpatterns = [
      path('robots.txt', robots_txt, name='robots_txt'),
      path('atousa/admin/panel/sina1234/', admin.site.urls),
      path('atousa/admin/panel/stats/', include('admin_panel.urls')),
      path('', include('home.urls')),
      path('user/', include('authentication.urls')),
      path('product/', include('products.urls')),
      path('cart/', include('orders.urls')),
      path('account/', include('account.urls')),
      path('us/', include('aboutus_contactus.urls')),
      path('article/', include('article.urls')),
      path('__debug__/', include(debug_toolbar.urls)),
      path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

orders/urls.py
from django.urls import path
from .Views import Cart_views, CreateOrderView, PaymentView, views

app_name = 'orders'
urlpatterns = [
    # Cart section Views
    path('add-to-cart-ajax/', Cart_views.add_to_cart_ajax, name='add_to_cart_ajax'),
    path('increase/', Cart_views.increase_quantity, name='cart_increase'),
    path('decrease/', Cart_views.decrease_quantity, name='cart_decrease'),
    path('del/order/', Cart_views.remove_from_cart, name='cart_del'),

    # Create order Views
    path('set-shipping-method/', CreateOrderView.set_shipping_method, name='set_shipping_method'),
    path('create-order/', CreateOrderView.create_order, name='cart_information'),

    # Orders Views
    path('detail/', views.OrderDetail.as_view(), name='cart_detail_page'),
    path('information/', views.InformationView.as_view(), name='cart_information_page'),
    path('payment/', views.PaymentView.as_view(), name='cart_payment_page'),
    path('apply-gift-code/', views.ApplyGiftCodeAjaxView.as_view(), name='apply_gift_code_ajax'),

    # PaymentViews
    path('pay/<int:order_id>/', PaymentView.order_payment_request, name='order_payment'),
    path('verify/', PaymentView.order_payment_verify, name='order_payment_verify'),
    path('success-payment/', PaymentView.payment_success, name='success_payment_page'),
    path('faild-payment/', PaymentView.payment_faild, name='faild_payment_page'),
]

aboutus_contactus/models.py
from django.core.cache import cache
from django.db import models
from django.contrib.auth import get_user_model

user_model = get_user_model()


class ContactUs(models.Model):
    tickets = [
        ('orders', 'سفارشات'), ('payment', 'امور مالی'), ('jobbing', 'همکاری'), ('guid', 'راهنمایی'), ('others', 'سایر')
    ]
    user = models.ForeignKey(user_model, on_delete=models.CASCADE, verbose_name='کاربر', related_name='contacts')
    ticket = models.CharField(max_length=100, choices=tickets, verbose_name='تیکت')
    text = models.TextField(verbose_name='متن پیام')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')
    answered = models.BooleanField(default=False, verbose_name='پاسخ داده شده ')

    class Meta:
        verbose_name = 'تیکت کاربر'
        verbose_name_plural = ' تیکت های کاربران'
        ordering = ['created_at', 'answered']

    def __str__(self):
        return f'{self.ticket} - {self.text:40}'


class ReplyContact(models.Model):
    reply_to = models.ForeignKey(ContactUs, on_delete=models.CASCADE, verbose_name='پاسخ به پیام',
                                 related_name='reply_contact', null=True, blank=True)
    user = models.ForeignKey(user_model, on_delete=models.CASCADE, verbose_name='کاربر', related_name='reply_contacts',
                             null=True, blank=True)
    text = models.TextField(verbose_name='متن پیام')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ پاسخ')
    is_read = models.BooleanField(default=False, verbose_name='خوانده شده ')

    class Meta:
        verbose_name = 'پاسخ به کاربر'
        verbose_name_plural = 'پاسخ به کاربران'
        ordering = ['created_at']

    def save(self, *args, **kwargs):
        cache_key = f'{self.user.id}_messages_count'
        cache.delete(cache_key)
        if not self.pk and self.reply_to:
            self.user = self.reply_to.user
        super().save(*args, **kwargs)
        if self.reply_to and not self.reply_to.answered:
            self.reply_to.answered = True
            self.reply_to.save(update_fields=['answered'])

    def __str__(self):
        return f'{self.reply_to} - {self.text:40}'

aboutus_contactus/forms.py
from django.forms import ModelForm
from .models import ContactUs
from django import forms


class ContactUsForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = ('ticket', 'text')
        widgets = {
            'ticket': forms.Select(attrs={
                'class': 'form-c',
            }),
            'text': forms.Textarea(attrs={
                'class': 'form-c',
                'placeholder': 'متن پیام',
                'rows': 4,
            }),
        }

aboutus_contactus/views.py
from django.contrib import messages
from django.core.paginator import EmptyPage, Paginator
from django.db.models import Prefetch
from django.http import Http404, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import View, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from account.models import WishList
from orders.form import UserAddressForm
from orders.cart import Cart
from .forms import ContactUsForm
from .models import ContactUs, ReplyContact
from orders.models import UserAddress, Order, OrderItem
from .utils import update_order_status
from account.utils import is_partner
from django.core.cache import cache


def about_us(request):
    return render(request, 'about-contact-us/about_us.html')


def contact_us(request):
    return render(request, 'about-contact-us/contact_us.html')


def rules(request):
    return render(request, 'about-contact-us/term.html')


class ContactView(LoginRequiredMixin, View):
    template_name = 'about-contact-us/contact.html'

    def get(self, request):
        form = ContactUsForm()
        context = {'form': form}
        return render(request, self.template_name, context)

    def post(self, request):
        form = ContactUsForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            from utils.telegram import notify_contact_us
            notify_contact_us(user=request.user, contact=cd['ticket'], message=cd['text'])
            ContactUs.objects.create(
                user=request.user,
                ticket=cd['ticket'],
                text=cd['text'],
            )

            messages.success(request, 'تیکت شما برای پشتیبانی ارسال شد')
            return redirect(reverse('contact_page'))
        return render(request, self.template_name, {'form': form})


class UserPanelView(LoginRequiredMixin, View):
    template_name = 'about-contact-us/user_panel.html'

    def get(self, request):
        user = request.user
        message = (
                ContactUs.objects.filter(user=user).count() +
                ReplyContact.objects.filter(user=user).count()
        )
        addresses = UserAddress.objects.filter(user=user).count()
        wishes = WishList.objects.filter(user=user).count()
        orders = Order.objects.filter(user=user).count()
        partner = is_partner(request)
        context = {'user': user, 'message': message, 'addresses': addresses, 'wishes': wishes, 'orders': orders,
                   'partner': partner}
        return render(request, self.template_name, context)


class UserContactListView(LoginRequiredMixin, ListView):
    model = ContactUs
    template_name = 'about-contact-us/contact-lists.html'
    context_object_name = 'contacts'

    def get_queryset(self):
        user = self.request.user
        ReplyContact.objects.filter(user=user, is_read=False).update(is_read=True)
        return ContactUs.objects.filter(user=user).prefetch_related(
            Prefetch('reply_contact', queryset=ReplyContact.objects.select_related('user'))
        ).order_by('-created_at')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        user = self.request.user

        contacts = ContactUs.objects.filter(user=user).prefetch_related(
            Prefetch('reply_contact', queryset=ReplyContact.objects.select_related('user'))
        )

        replies = ReplyContact.objects.filter(user=user, reply_to__isnull=True)

        combined = []

        for contact in contacts:
            combined.append({
                'type': 'contact',
                'object': contact,
                'created_at': contact.created_at
            })
            for reply in contact.reply_contact.all():
                combined.append({
                    'type': 'reply',
                    'object': reply,
                    'created_at': reply.created_at
                })

        for reply in replies:
            combined.append({
                'type': 'standalone',
                'object': reply,
                'created_at': reply.created_at
            })

        context['contacts'] = sorted(combined, key=lambda x: x['created_at'], reverse=True)
        return context


class UserAddressView(LoginRequiredMixin, View):
    template_name = 'about-contact-us/user_address.html'

    def get(self, request):
        user = request.user
        addresses = UserAddress.objects.filter(user=user)

        address_form = UserAddressForm()
        context = {
            'address_form': address_form,
            'addresses': addresses,
        }
        return render(request, self.template_name, context)

    def post(self, request):
        address_form = UserAddressForm(request.POST)

        if address_form.is_valid():
            cd = address_form.cleaned_data
            user = request.user
            address = UserAddress.objects.filter(
                user=user,
                province=cd['province'],
                city=cd['city'],
                address=cd['address'],
                postal_code=cd['postal_code'],
                phone=cd['phone']
            ).first()
            if not address:
                address = UserAddress.objects.create(
                    user=user,
                    first_name=cd['first_name'],
                    last_name=cd['last_name'],
                    province=cd['province'],
                    city=cd['city'],
                    address=cd['address'],
                    postal_code=cd['postal_code'],
                    phone=cd['phone'],
                )
            messages.success(request, 'آدرس شما با موفقیت ثبت شد')
            return redirect(reverse('user_address_page'))
        addresses = UserAddress.objects.filter(user=request.user)
        context = {
            'address_form': address_form,
            'addresses': addresses,
        }

        return render(request, self.template_name, context=context)


class UserOrdersView(View):
    template_name = 'about-contact-us/user_orders.html'

    def get(self, request):
        orders = list(Order.objects.filter(user=request.user, paid=True).order_by('-updated'))

        orders_packing = 0
        orders_sending = 0
        orders_finished = 0

        for order in orders:
            update_order_status(order)
            if not order.get_in_post and not order.finished:
                orders_packing += 1
            if order.get_in_post and not order.finished:
                orders_sending += 1
            if order.finished and not order.get_in_post:
                orders_finished += 1

        context = {
            'orders_sending': orders_sending,
            'orders_packing': orders_packing,
            'orders_finished': orders_finished,
        }
        return render(request, 'about-contact-us/user_orders.html', context)


class UserOrdersAjaxView(View):
    def get(self, request, status):
        if status == 'cart':
            cart = Cart(request)
            return render(request, 'partial/order_list_partial.html', {'cart': cart, 'status': status})
        status_map = {
            'packing': lambda o: o.paid and not o.get_in_post and not o.finished,
            'sending': lambda o: o.paid and o.get_in_post and not o.finished,
            'finished': lambda o: o.paid and o.finished and not o.get_in_post,
        }

        if status not in status_map:
            raise Http404()

        orders = list(Order.objects
                      .filter(user=request.user, paid=True)
                      .select_related('address')
                      .prefetch_related(Prefetch('items', queryset=OrderItem.objects.select_related('product')))
                      .order_by('-updated'))

        filtered_orders = [o for o in orders if status_map[status](o)]

        paginator = Paginator(filtered_orders, 5)
        page_number = request.GET.get('page', 1)

        try:
            page_obj = paginator.page(page_number)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        return render(request, 'partial/order_list_partial.html', {
            'orders': page_obj.object_list,
            'page_obj': page_obj,
            'paginator': paginator,
            'status': status,
        })


def get_user_counts(request):
    if not request.user.is_authenticated:
        return JsonResponse({'wishlist_count': 0, 'messages_count': 0})

    wishlist_count = WishList.objects.filter(user=request.user).count()
    messages_count = ReplyContact.objects.filter(user=request.user, is_read=False).count()

    return JsonResponse({
        'wishlist_count': wishlist_count,
        'messages_count': messages_count,
    })

aboutus_contactus/templates/about-contact-us/about_us.html
{% extends 'base/index.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href={% static "css/aboutandcontactus.css" %}>{% endblock %}
{% block title %}
    درباره فروشگاه لباس آتوسا | کیفیت، تنوع و اعتماد
{% endblock %}

{% block meta %}
    <meta name="description"
          content="با فروشگاه لباس آتوسا بیشتر آشنا شوید. تجربه‌ای نو در خرید لباس کودک، زنانه و ست مادر فرزندی با کیفیت بالا، ارسال سریع و پشتیبانی اختصاصی.">
    <meta name="keywords"
          content="درباره فروشگاه لباس, لباس بچه, لباس زنانه, فروشگاه آتوسا, ست مادر و فرزند, خرید لباس آنلاین">
{% endblock %}

{% block og_title %}درباره فروشگاه آتوسا{% endblock %}
{% block og_description %}آشنایی با فروشگاه لباس آتوسا - تخصصی‌ترین فروشگاه لباس کودک و زنانه با خدمات مشتری‌مدار و
    محصولات باکیفیت.{% endblock %}
{% block og_image %}/static/image/about-us.jpg{% endblock %}

{% block twitter_title %}درباره ما | فروشگاه لباس آتوسا{% endblock %}
{% block twitter_description %}با فروشگاه آتوسا بیشتر آشنا شوید؛ کیفیت، پشتیبانی، تنوع بالا و ارسال سریع برای خریدی
    مطمئن.{% endblock %}
{% block twitter_image %}/static/image/about-us.jpg{% endblock %}

{% block content %}
    <div id="about-us-container">
        <img src="/static/image/about-us.jpg" alt="درباره فروشگاه لباس آتوسا">
        <section class="about-section">


            <div class="about-block">
                <div class="about-text">
                    <h2>آشنایی با فروشگاه <strong> آتوسا </strong></h2>
                    <p>
                        آتوسا یک فروشگاه اینترنتی تخصصی در زمینه پوشاک بچگانه است که با عشق به کودکان و سلیقه والدین شکل
                        گرفته.
                        ما مجموعه‌ای از بهترین لباس‌های کودک را از برندهای معتبر ایرانی و اروپایی گلچین کرده‌ایم تا هم
                        شیک و باکیفیت باشند، هم راحت و سلامت‌محور.

                        در فروشگاه آتوسا، تلاش کرده‌ایم تجربه خرید آنلاین را برای والدین ساده، مطمئن و لذت‌بخش کنیم؛ از
                        انتخاب
                        سایز گرفته تا تحویل سریع درب منزل، همه چیز طوری طراحی شده که شما با خیال راحت خرید کنید و
                        فرزندتان بدرخشد.

                        ما اینجاییم تا بهترین‌ها را برای فرزندتان فراهم کنیم.
                    </p>
                </div>
                <div class="about-image">
                    <img src="/static/image/icons/aboutus.webp" alt="داستان ما">
                </div>
            </div>


            <div class="about-block reverse">
                <div class="about-image">
                    <img src="/static/image/icons/easybuy.webp" alt="ماموریت ما">
                </div>
                <div class="about-text">
                    <h2>خرید آسان و بی‌دغدغه از آتوسا</h2>
                    <p>
                        در فروشگاه آتوسا، راحتی و آرامش شما هنگام خرید برای ما اهمیت بالایی دارد. به همین دلیل تمام
                        بخش‌های
                        فروشگاه طوری طراحی شده‌اند که حتی اگر اولین بار است آنلاین لباس بچگانه می‌خرید، با خیال راحت و
                        بدون نگرانی انتخاب کنید.

                        برای هر محصول، تصاویر باکیفیت و واضح از همه رنگ‌ها و زوایا قرار داده‌ایم تا دقیقاً بدانید چه
                        چیزی دریافت خواهید کرد.

                        کنار هر لباس، راهنمای دقیق سایز و اندازه‌ها بر اساس سن، قد و وزن کودک ارائه شده تا انتخاب درستی
                        داشته باشید — بدون نیاز به حدس زدن یا نگرانی از کوچک یا بزرگ بودن.

                        علاوه بر این، در صفحات محصول، توضیحات کامل، جنس پارچه، کاربرد و نکات شست‌وشو هم آورده شده تا همه
                        چیز شفاف و قابل اعتماد باشد.

                        با آتوسا، خرید لباس کودک دیگر وقت‌گیر و استرس‌زا نیست. فقط ببینید، انتخاب کنید، و مطمئن باشید که
                        بهترین انتخاب را انجام داده‌اید.
                    </p>
                </div>
            </div>


            <div class="about-block">
                <div class="about-text">
                    <h2>پشتیبانی ۲۴ ساعته، همیشه همراه شما</h2>
                    <p>
                        در فروشگاه آتوسا تنها نیستید؛ ما ۷ روز هفته، ۲۴ ساعته کنار شماییم تا تجربه‌ای مطمئن و
                        دلگرم‌کننده از خرید داشته باشید.

                        چه در انتخاب لباس و سایز سوالی داشته باشید، چه در روند خرید و پرداخت یا حتی پس از سفارش، تیم
                        پشتیبانی ما با پاسخ‌گویی سریع، دلسوزانه و حرفه‌ای آماده کمک به شماست.

                        می‌تونید از طریق ثبت تیکت داخل سایت یا پیام به ما در شبکه‌های اجتماعی با مشاوران آتوسا در ارتباط
                        باشید و مطمئن باشید که پاسخ‌تان را در کوتاه‌ترین زمان ممکن دریافت خواهید کرد.

                        با آتوسا، پشتیبانی فقط یک شعار نیست یه همراهیه واقعیه.


                    </p>
                    <a href="{% url 'contact_us_page' %}" class="about-btn">تماس با ما</a>
                </div>
                <div class="about-image">
                    <img src="/static/image/icons/gback.webp" alt="تیم ما">
                </div>
            </div>

        </section>
    </div>
{% endblock %}

aboutus_contactus/templates/about-contact-us/contact-lists.html
{% extends 'base/index.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href={% static "css/messages.css" %}>{% endblock %}
{% load jformat %}

{% block title %}
    پیام‌های من | گفت‌وگو با پشتیبانی آتوسا
{% endblock %}

{% block meta %}
    <meta name="description"
          content="در این صفحه می‌توانید پیام‌های ارسالی خود به پشتیبانی فروشگاه لباس آتوسا و پاسخ‌های کارشناسان را مشاهده کنید.">
    <meta name="robots" content="noindex, nofollow">
{% endblock %}

{% block og_title %}پیام‌های شما{% endblock %}
{% block og_description %}نمایش پیام‌های شما و پاسخ‌های پشتیبانی فروشگاه آتوسا.{% endblock %}
{% block og_image %}/static/image/contact.jpg{% endblock %}

{% block twitter_title %}گفت‌وگو با پشتیبانی | فروشگاه آتوسا{% endblock %}
{% block twitter_description %}پیام‌ها و پاسخ‌های شما با پشتیبانی فروشگاه آتوسا در این صفحه نمایش داده
    می‌شود.{% endblock %}
{% block twitter_image %}/static/image/contact.jpg{% endblock %}

{% block content %}
    <div class="chat-container">
        {% for item in contacts %}
            {% if item.type == 'contact' %}
                <div class="message-wrapper {% if item.object.answered %}answered{% else %}unanswered{% endif %}">
                    <div class="message user-message">
                        <div class="user-m">
                            <h2 class="owner-m">پیام شما</h2>
                            <h3>موضوع : {{ item.object.get_ticket_display }}</h3>
                        </div>
                        <div class="messages-c">
                            <p>{{ item.object.text }}</p>
                            <p class="date-m">{{ item.object.created_at|jformat:"%Y/%m/%d" }}</p>
                        </div>
                        {% if item.object.answered %}
                            <span class="status-icon">✔️</span>
                        {% endif %}
                    </div>
                </div>
            {% elif item.type == 'reply' %}
                <div class="message reply-message">
                    <h2 class="owner-m" id="admin-m">پاسخ ادمین</h2>
                    <div class="messages-c">
                        <p>{{ item.object.text }}</p>
                        <p class="date-m">{{ item.object.created_at|jformat:"%Y/%m/%d" }}</p>
                    </div>
                </div>
            {% elif item.type == 'standalone' %}
                <div class="message reply-message">
                    <h2 class="owner-m" id="admin-m">پیام سیستم</h2>
                    <div class="messages-c">
                        <p>{{ item.object.text }}</p>
                        <p class="date-m">{{ item.object.created_at|jformat:"%Y/%m/%d" }}</p>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

aboutus_contactus/templates/about-contact-us/contact.html
{% extends 'base/index.html' %}
{% load static %}
{% block css %}<link rel="stylesheet" href={% static "css/form_base.css" %}>{% endblock %}
{% block title %}
    ارسال تیکت پشتیبانی | ارتباط با فروشگاه لباس آتوسا
{% endblock %}

{% block meta %}
    <meta name="description"
          content="اگر سوال یا مشکلی دارید، از طریق فرم ارسال تیکت با پشتیبانی فروشگاه لباس آتوسا در تماس باشید. پاسخ‌گویی سریع و دقیق توسط تیم پشتیبانی ما.">
    <meta name="keywords"
          content="ارسال تیکت, پشتیبانی فروشگاه لباس, تماس با آتوسا, پشتیبانی مشتریان, فرم تماس با ما, مشکل در سفارش">
{% endblock %}

{% block og_title %}ارتباط با پشتیبانی فروشگاه آتوسا{% endblock %}
{% block og_description %}برای هرگونه سوال، درخواست یا مشکل، می‌توانید از فرم تیکت استفاده کرده و پاسخ سریع تیم پشتیبانی
    ما را دریافت کنید.{% endblock %}
{% block og_image %}/static/image/contact.jpg{% endblock %}

{% block twitter_title %}ارسال تیکت پشتیبانی | آتوسا{% endblock %}
{% block twitter_description %}از طریق فرم تیکت فروشگاه آتوسا، با پشتیبانی در ارتباط باشید. پاسخ سریع و حرفه‌ای در
    کمترین زمان.{% endblock %}
{% block twitter_image %}/static/image/contact.jpg{% endblock %}

{% block content %}
    <section class="book" id="form_auth">
        <div id="form-ui">
            <img id=cover_img src="/static/image/contact.jpg" alt="ارسال تیکت پشتیبانی فروشگاه آتوسا">
            <form action="{% url 'contact_page' %}" method="post" id="form-contact">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{ request.GET.next|default:'/' }}">
                <img id="logo_form" src="/static/image/icons/forms.png" alt="لوگوی فروشگاه لباس آتوسا">
                <div id="form-body">
                    <div id="welcome-lines">
                        <div id="welcome-line-1">ارسال تیکت به پشتیبانی</div>
                        <p>درخواست خود را به صورت یک تیکت مطرح کنید تا کارشناسان ما در اسرع وقت، به آن پاسخ دهند</p>
                    </div>
                    <div id="input-area">
                        {% for field in form %}
                            <div class="form-c">
                                {{ field }}
                                {% for error in field.errors %}
                                    <div class="error-msg">{{ error }}</div>
                                {% endfor %}
                            </div>
                        {% endfor %}
                    </div>
                    <div id="submit-button-cvr">
                        <button id="send-btn" type="submit">ارسال</button>
                    </div>
                    {% if error %}
                        <div class="error-msg">{{ error }}</div>
                    {% endif %}
                </div>
            </form>
        </div>
    </section>
{% endblock %}

aboutus_contactus/templates/about-contact-us/user_orders.html
{% extends 'base/index.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href={% static "css/user_panel.css" %}>
    <link rel="stylesheet" href={% static "css/custom_cart.css" %}>
    <link rel="stylesheet" href={% static "css/cart_detail.css" %}>
{% endblock %}
{% block meta %}
    <meta name="robots" content="noindex, nofollow">
{% endblock %}
{% block title %}
    پیگیری سفارشات
{% endblock %}
{% block content %}
    <div id="user-panel-container">
        <div class="custom-main" id="user-order-page">
            <div class="box-wrapper" style="--main-color: #99689C">
                <div class="custom-glass-box custom-glass-boxes" id="orders-b">
                    <div class="box-title"><h2>سبد خرید فعلی </h2></div>
                    <div class="user-count">{% if cart_item_count != 0 %}
                        1 {% else %} 0
                    {% endif %} </div>
                </div>
            </div>
            <div class="box-wrapper" style="--main-color: #9C655B">
                <div class="custom-glass-box custom-glass-boxes" id="wish-b">
                    <div class="box-title"><h2> آماده سازی</h2></div>
                    <div class="user-count">{{ orders_packing }}</div>
                </div>
            </div>
            <div class="box-wrapper" style="--main-color: #9C9C61">
                <div class="custom-glass-box custom-glass-boxes" id="address-b">
                    <div class="box-title"><h2>در حال ارسال</h2></div>
                    <div class="user-count">{{ orders_sending }}</div>
                </div>
            </div>

            <div class="box-wrapper" style="--main-color: #538E4F">
                <div class="custom-glass-box custom-glass-boxes" id="contacts-b">
                    <div class="box-title"><h2>تحویل گرفته</h2></div>
                    <div class="user-count">{{ orders_finished }}</div>
                </div>
            </div>
        </div>
        <div class="orders-list" id="current-o">
            {% if cart %}
                <div class="sub-cart">
                    <div class="cart-items-o">{% include 'cart/cart_items_partial.html' with item=cart %}</div>
                    <a class="sub-cart-img" href="{% url 'orders:cart_detail_page' %}"><img
                            src="/static/image/icons/complete-o.png" alt="">سبد خرید فعلی شما</a>
                </div>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block js %}<script src={% static "js/user_panel_orders.js" %}></script>{% endblock %}