bache_poosh/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home.views import robots_txt
from django.contrib.sitemaps.views import sitemap
from home.site_map import StaticViewSitemap, ProductSitemap, ArticleSitemap, ArticleCategorySitemap
sitemaps = {
    'products': ProductSitemap,
    'categories': StaticViewSitemap,
    'articles': ArticleSitemap,
    'articles_cat': ArticleCategorySitemap,
}
urlpatterns = [
      path('robots.txt', robots_txt, name='robots_txt'),
      path('atousa/admin/panel/sina1234/', admin.site.urls),
      path('atousa/admin/panel/stats/', include('admin_panel.urls')),
      path('', include('home.urls')),
      path('user/', include('authentication.urls')),
      path('product/', include('products.urls')),
      path('cart/', include('orders.urls')),
      path('account/', include('account.urls')),
      path('us/', include('aboutus_contactus.urls')),
      path('article/', include('article.urls')),
      path('__debug__/', include(debug_toolbar.urls)),
      path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

orders/urls.py
from django.urls import path
from .Views import Cart_views, CreateOrderView, PaymentView, views

app_name = 'orders'
urlpatterns = [
    # Cart section Views
    path('add-to-cart-ajax/', Cart_views.add_to_cart_ajax, name='add_to_cart_ajax'),
    path('increase/', Cart_views.increase_quantity, name='cart_increase'),
    path('decrease/', Cart_views.decrease_quantity, name='cart_decrease'),
    path('del/order/', Cart_views.remove_from_cart, name='cart_del'),

    # Create order Views
    path('set-shipping-method/', CreateOrderView.set_shipping_method, name='set_shipping_method'),
    path('create-order/', CreateOrderView.create_order, name='cart_information'),

    # Orders Views
    path('detail/', views.OrderDetail.as_view(), name='cart_detail_page'),
    path('information/', views.InformationView.as_view(), name='cart_information_page'),
    path('payment/', views.PaymentView.as_view(), name='cart_payment_page'),
    path('apply-gift-code/', views.ApplyGiftCodeAjaxView.as_view(), name='apply_gift_code_ajax'),

    # PaymentViews
    path('pay/<int:order_id>/', PaymentView.order_payment_request, name='order_payment'),
    path('verify/', PaymentView.order_payment_verify, name='order_payment_verify'),
    path('success-payment/', PaymentView.payment_success, name='success_payment_page'),
    path('faild-payment/', PaymentView.payment_faild, name='faild_payment_page'),
]

orders/models.py
from django.db import models
from django.contrib.auth import get_user_model
from .utils import generate_unique_product_code
from django.core.cache import cache

User = get_user_model()


class Order(models.Model):
    SHIPPING_CHOICES = [
        ('pishteaz', 'پست پیشتاز'),
        ('tipax', 'ارسال با تیپاکس'),
    ]
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر ')
    total_price = models.PositiveIntegerField(blank=True, null=True, verbose_name='جمع فاکتور')
    paid = models.BooleanField(verbose_name='پرداخت شده ؟', default=False)
    TrackingCode = models.CharField(max_length=100, verbose_name='کد رهگیری', null=True, blank=True)
    get_in_post = models.BooleanField(default=False, verbose_name='به پست تحویل داده شد')
    finished = models.BooleanField(default=False, verbose_name='به دست کاربر رسید')
    code = models.PositiveIntegerField(null=True, blank=True, verbose_name='شماره فاکتور')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True, verbose_name='آخرین آپدیت')
    address = models.ForeignKey('UserAddress', on_delete=models.SET_NULL, null=True, blank=True,
                                verbose_name='آدرس ارسال')
    shipping_method = models.CharField(
        max_length=20,
        choices=SHIPPING_CHOICES,
        default='pishteaz',
        verbose_name='روش ارسال'
    )
    authority = models.CharField(max_length=255, null=True, blank=True, verbose_name='کد مرجع زرین‌پال')
    ref_id = models.CharField(max_length=255, null=True, blank=True, verbose_name='شماره پیگیری پرداخت')

    class Meta:
        ordering = ['-created']
        db_table = 'orders'
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'

    def save(self, *args, **kwargs):
        if self.TrackingCode and not self.get_in_post and not self.finished:
            self.get_in_post = True
            cache_key = f'order-{self.code}'
            cache.set(cache_key, True, timeout=604800)
        if not self.code:
            self.code = generate_unique_product_code()
        super().save(*args, **kwargs)

    def get_total_items_price(self):
        total_price = sum(item.price for item in self.items.all())
        return total_price

    def get_shipping_price(self):
        if self.shipping_method == 'pishteaz':
            return 0 if self.get_total_items_price() >= 2000000 else 69000
        elif self.shipping_method == 'tipax':
            return 0

    def get_final_price(self):
        return self.get_total_items_price() + self.get_shipping_price()

    def __str__(self):
        return f'{self.user}-{self.id}'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='سفارش', related_name='items')
    product = models.ForeignKey('products.ProductVariant', on_delete=models.CASCADE, verbose_name='محصول')
    price = models.IntegerField(verbose_name='قیمت محصول')
    discount = models.PositiveIntegerField(verbose_name='تخفیف', default=0)
    quantity = models.IntegerField(default=1, verbose_name='تعداد')

    class Meta:
        verbose_name = 'محصول سبد خرید'
        verbose_name_plural = 'محصولات سبد های خرید'
        db_table = 'order_items'

    def __str__(self):
        return f'{self.order}'


class UserAddress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    first_name = models.CharField(max_length=100, verbose_name='نام')
    last_name = models.CharField(max_length=100, verbose_name='نام خانوادگی')
    province = models.CharField(max_length=50, verbose_name='استان')
    city = models.CharField(max_length=50, verbose_name='شهر')
    address = models.CharField(max_length=150, verbose_name='آدرس')
    postal_code = models.CharField(max_length=15, verbose_name='کد پستی')
    phone = models.CharField(max_length=15, verbose_name='شماره تماس گیرنده')

    class Meta:
        verbose_name = 'آدرس کاربر'
        verbose_name_plural = 'آدرس کاربران'
        db_table = 'user_address'

    def __str__(self):
        return f'{self.first_name}-{self.last_name}-{self.province}-{self.city}-{self.address}-{self.phone}'

orders/Views/views.py
from django.db.models import Prefetch
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View
from orders.cart import Cart
from orders.form import UserAddressForm, GiftCodeForm
from orders.mixins import CartRequiredMixin
from orders.models import Order, OrderItem, UserAddress


class OrderDetail(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'cart/cart_detail.html', {'cart': cart})


class InformationView(CartRequiredMixin, View):
    template_name = 'cart/information.html'

    def get(self, request):
        user = request.user
        addresses = UserAddress.objects.filter(user=user)

        address_form = UserAddressForm()
        cart = Cart(request)
        if 'shipping_method' not in request.session:
            request.session['shipping_method'] = 'pishteaz'
        context = {
            'cart': cart,
            'address_form': address_form,
            'addresses': addresses,
            'shipping_method': request.session['shipping_method'],
        }
        return render(request, self.template_name, context)

    def post(self, request):
        address_form = UserAddressForm(request.POST)

        if address_form.is_valid():
            cd = address_form.cleaned_data
            user = request.user
            order = user.order_set.filter(paid=False).last()
            send_method = request.session.get('shipping_method')
            order.shipping_method = send_method
            order.total_price = order.get_final_price()
            order.save()
            address = UserAddress.objects.filter(
                user=user,
                province=cd['province'],
                city=cd['city'],
                address=cd['address'],
                postal_code=cd['postal_code'],
                phone=cd['phone']
            ).first()
            if not address:
                address = UserAddress.objects.create(
                    user=user,
                    first_name=cd['first_name'],
                    last_name=cd['last_name'],
                    province=cd['province'],
                    city=cd['city'],
                    address=cd['address'],
                    postal_code=cd['postal_code'],
                    phone=cd['phone'],
                    order=order
                )
            order.address = address
            order.save()

            return redirect(reverse('orders:cart_payment_page'))
        cart = Cart(request)
        addresses = UserAddress.objects.filter(user=request.user)
        context = {
            'cart': cart,
            'address_form': address_form,
            'addresses': addresses,
        }

        return render(request, self.template_name, context=context)


class PaymentView(CartRequiredMixin, View):
    template_name = 'cart/payment.html'

    def get(self, request):
        order = Order.objects.filter(user=request.user, paid=False).prefetch_related(
            Prefetch('items',
                     queryset=OrderItem.objects.select_related('product__product', 'product__color', 'product__size'))
        ).last()

        if not order:
            return redirect('orders:cart_detail_page')

        return render(request, self.template_name, {
            'order': order,
            'order_items': order.items.all(),
        })


class ApplyGiftCodeAjaxView(View):
    def post(self, request, *args, **kwargs):
        form = GiftCodeForm(request.POST, request=request)
        if form.is_valid():
            gift = form.gift
            valid = gift.is_valid()
            if valid:
                request.session['gift'] = {
                    'code': gift.gift_code,
                    'percent': gift.percent,
                    'partner_id': gift.partner_id,
                }
                request.session['ref_code'] = gift.partner.code
                request.session.modified = True
                cart = Cart(request)
                return JsonResponse({
                    'success': True,
                    'message': f'کد تخفیف "{gift.gift_code}" با موفقیت اعمال شد.',
                    'percent': gift.percent,
                    'total_price': cart.get_total_price(),
                    'total_discount': cart.get_total_discount(),
                    'send_free': cart.send_free(),
                })
            return JsonResponse({'errors': form.errors.as_json()}, status=400)
        else:
            return JsonResponse({'errors': form.errors.as_json()}, status=400)

orders/templates/cart/partial/faild-pay.html
{% extends 'base/index.html' %}
{% block meta %}
	<meta name="robots" content="noindex, nofollow">
{% endblock %}
{% load price_filters %}
{% load jformat %}
{% block title %}
    پرداخت ناموفق
{% endblock %}
{% block content %}
    <div class="container-c" id="container-f">
        <div class="c">
            <div class="i"><img src="/static/image/-%20Copy.png" alt="">
                <div id="success-t">
                    <h1 class="h f">پرداخت شما ناموفق بود!</h1>
                    <p class="p">متأسفانه پرداخت شما با موفقیت انجام نشد یا توسط شما لغو شد.</p>
                </div>
            </div>
            <h3 id="faild-info">ممکن است یکی از موارد زیر باعث این خطا شده باشد</h3>
            <div id="faild-pay-info-section">
                <h3 class="pay-info f">مشکل در اتصال اینترنت</h3>
                <h3 class="pay-info f">عدم موجودی</h3>
                <h3 class="pay-info f">پرداخت را لغو کرده باشید</h3>
                <h3 class="pay-info f">لطفاً در صورت اطمینان از صحت اطلاعات، مجدداً تلاش نمایید.</h3>
            </div>

            <div id="success-pay-btns">
                <a href="{% url 'orders:order_payment' order.id %}" class="b fb">تلاش مجدد</a>
                <a href="{% url 'orders:cart_detail_page' %}" class="b fb">بازگشت به سبد خرید</a>
            </div>
        </div>
    </div>
{% endblock %}

orders/templates/cart/partial/gift_code_partial.html
<form id="gift-code-form">
    <input type="text" id="gift_code" name="gift_code" placeholder="کد تخفیف را وارد کنید"/>
    <button class="checkout-btn" id="gift-btn" type="submit">اعمال کد</button>
</form>
<div id="gift-code-message"></div>

orders/templates/cart/partial/success_pay.html
{% extends 'base/index.html' %}
{% block meta %}
	<meta name="robots" content="noindex, nofollow">
{% endblock %}
{% load price_filters %}
{% load jformat %}
{% block title %}
    پرداخت موفق
{% endblock %}
{% block content %}
    <div class="container-c">
        <div class="c">
            <div class="i"><img src="/static/image/-%20Copy.png" alt="">
                <div id="success-t">
                    <h1 class="h">پرداخت شما با موفقیت انجام شد!</h1>
                    <p class="p">از خرید شما سپاسگزاریم</p>
                </div>
            </div>

            <div id="pay-info-section">
                <h3 class="pay-info">مبلغ پرداخت شده : <span>{{ order.total_price|format_price }}</span></h3>
                <h3 class="pay-info">کد رهگیری : <span>{{ order.ref_id }}</span></h3>
                <h3 class="pay-info">تاریخ : <span>{{ order.updated|jformat:"%Y/%m/%d" }}</span></h3>
                <h3 class="pay-info">ساعت : <span>{{ order.updated|jformat:"%H:%M:%S" }}</span></h3>
                <h3 class="pay-info" id="last-i">روش ارسال : <span>{{ order.get_shipping_method_display}}</span></h3>
            </div>

            <div id="success-pay-btns">
                <a href="/" class="b">بازگشت به صفحه اصلی</a>
                <a href="{% url 'user_orders_page' %}" class="b">پیگیری سفارش</a>
            </div>
        </div>
    </div>
{% endblock %}