bache_poosh/urls.py
import debug_toolbar
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from home.views import robots_txt
from django.contrib.sitemaps.views import sitemap
from home.site_map import StaticViewSitemap, ProductSitemap, ArticleSitemap, ArticleCategorySitemap
sitemaps = {
    'products': ProductSitemap,
    'categories': StaticViewSitemap,
    'articles': ArticleSitemap,
    'articles_cat': ArticleCategorySitemap,
}
urlpatterns = [
      path('robots.txt', robots_txt, name='robots_txt'),
      path('atousa/admin/panel/sina1234/', admin.site.urls),
      path('atousa/admin/panel/stats/', include('admin_panel.urls')),
      path('', include('home.urls')),
      path('user/', include('authentication.urls')),
      path('product/', include('products.urls')),
      path('cart/', include('orders.urls')),
      path('account/', include('account.urls')),
      path('us/', include('aboutus_contactus.urls')),
      path('article/', include('article.urls')),
      path('__debug__/', include(debug_toolbar.urls)),
      path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
]

products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('list/', views.ProductVariantListView.as_view(), name='product_list_page'),
    path('categories/', views.category_view, name='categories_list_page'),
    path('ajax/filter-products/', views.ajax_product_filter, name='ajax_filter_products'),
    path('<int:code>/<str:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('get-variants/', views.get_variants, name='get_variants'),
    path('ajax/search-suggestions/', views.search_suggestions_api, name='search_suggestions'),
]

products/models.py
from django.core.cache import cache
from django.db import models
from django.db.models import Sum
from django.urls import reverse
from django.utils.text import slugify
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from .utils import generate_unique_product_code
from account.models import User


class Base(models.Model):
    title = models.CharField(max_length=100, verbose_name='عنوان', db_index=True)
    slug = models.CharField(max_length=100, unique=True, verbose_name='اسلاگ', null=True, blank=True, db_index=True)
    is_active = models.BooleanField(default=True, db_index=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        super().save(*args, **kwargs)
        cache.delete('categories')
        return self.slug

    class Meta:
        abstract = True


class Category(Base):
    sub_category = models.ForeignKey('self', on_delete=models.CASCADE, blank=True, null=True,
                                     verbose_name='دسته بندی اصلی', related_name='sub_categories')
    image = ProcessedImageField(
        null=True,
        blank=True,
        upload_to='products/',
        processors=[ResizeToFill(200, 200)],
        format='WEBP',
        options={'quality': 100}
    )

    class Meta:
        db_table = 'category'
        verbose_name = 'دسته بندی'
        verbose_name_plural = 'دسته بندی ها'
        ordering = ['title']

    def __str__(self):
        return self.title


    def get_all_subcategories(self):
        subcategories = list(self.sub_categories.all())
        for subcat in self.sub_categories.all():
            subcategories += subcat.get_all_subcategories()
        return subcategories

    def get_category_ancestors(self):
        ancestors = []
        category = self
        while category:
            ancestors.insert(0, category)
            category = category.sub_category
        return ancestors

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        cache.delete('categories')

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        cache.delete('categories')


class Color(models.Model):
    title = models.CharField(max_length=20, verbose_name='نام رنگ')
    hex_color = models.CharField(max_length=7, verbose_name='شناسه رنگ')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'colors'
        verbose_name = 'رنگ'
        verbose_name_plural = 'رنگ ها'
        ordering = ['title']


class Size(models.Model):
    title = models.CharField(max_length=10, verbose_name='سایز')
    age_min = models.CharField(max_length=50, null=True, blank=True, verbose_name="حداقل سن")
    age_max = models.CharField(max_length=50, null=True, blank=True, verbose_name='حداکثر سن')

    def __str__(self):
        return f"{self.title} (برای {self.age_min} تا {self.age_max})"

    class Meta:
        db_table = 'sizes'
        verbose_name = 'سایز'
        verbose_name_plural = 'سایز ها'
        ordering = ['title']


class Product(Base):
    MATERIAL_CHOICES = [
        ('cotton', 'پنبه‌ای'),
        ('linen', 'کتان'),
        ('polyester', 'پلی‌استر'),
        ('wool', 'پشمی'),
        ('silk', 'ابریشم'),
    ]
    GENDER_CHOICES = [
        ('boys', 'پسرانه'),
        ('girls', 'دخترانه'),
        ('unisex', 'هر دو'),
    ]

    category = models.ForeignKey('Category', on_delete=models.CASCADE, blank=True, null='True',
                                 verbose_name='دسته بندی', related_name='products')
    slug = models.CharField(max_length=100, verbose_name='اسلاگ', null=True, blank=True, db_index=True)
    model = models.CharField(max_length=50, verbose_name='مدل محصول', null=True, blank=True, db_index=True)
    discount = models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف', null=True, blank=True)
    has_discount = models.BooleanField(default=False, verbose_name='آیا محصول تخفیف دارد؟')
    discount_expiry = models.DateTimeField(null=True, blank=True, verbose_name='تاریخ انقضا تخفیف')
    price = models.IntegerField(verbose_name='قیمت محصول', db_index=True)
    age = models.CharField(max_length=70, verbose_name='مناسب چه بازه سنی', null=True, blank=True)

    description = models.TextField(verbose_name='توضیحات کامل')
    material = models.CharField(max_length=100, choices=MATERIAL_CHOICES, verbose_name='جنس محصول')
    gender = models.CharField(max_length=100, choices=GENDER_CHOICES, verbose_name='جنسیت')
    image = ProcessedImageField(
        null=True,
        blank=True,
        upload_to='products/',
        processors=[ResizeToFill(270, 334)],
        format='WEBP',
        options={'quality': 100}
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    code = models.PositiveIntegerField(unique=True, null=True, blank=True)
    views = models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')
    total_stock = models.PositiveIntegerField(default=0, verbose_name='موجودی کل')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title, allow_unicode=True)
        if not self.code:
            self.code = generate_unique_product_code()
        super().save(*args, **kwargs)
        self.clear_homepage_caches()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self.clear_homepage_caches()

    def get_discounted_price(self):
        discount = (self.discount / 100) * int(self.price)
        return self.price - discount

    class Meta:
        db_table = 'product'
        verbose_name = 'محصول'
        verbose_name_plural = 'محصولات'
        ordering = ['title']

    def get_absolute_url(self):
        return reverse('product_detail', args=[self.code, self.slug])

    def clear_homepage_caches(self):
        cache.delete('homepage_most_discount')
        cache.delete('homepage_most_recent')
        cache.delete('homepage_most_viewed')


class ProductVariant(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='محصول', related_name='variants')
    color = models.ForeignKey('Color', on_delete=models.CASCADE, verbose_name='رنگ')
    size = models.ForeignKey('Size', on_delete=models.CASCADE, verbose_name='سایز')
    discount = models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف', null=True, blank=True)
    has_discount = models.BooleanField(default=False, verbose_name='آیا محصول تخفیف دارد؟')
    price = models.IntegerField(verbose_name='قیمت محصول')
    is_active = models.BooleanField(default=True, verbose_name='موجود است')
    image = ProcessedImageField(
        null=True,
        blank=True,
        upload_to='products/variant/',
        processors=[ResizeToFill(350, 433)],
        format='WEBP',
        options={'quality': 100}
    )
    stock = models.PositiveIntegerField(default=0, verbose_name='موجودی')

    class Meta:
        unique_together = ('product', 'color', 'size')
        db_table = 'product_variant'
        verbose_name = 'دسته کردن محصول'
        verbose_name_plural = 'دسته کردن محصولات'
        ordering = ['product', 'color']

    def save(self, *args, **kwargs):
        self.is_active = self.stock > 0
        super().save(*args, **kwargs)
        total = ProductVariant.objects.filter(product=self.product).aggregate(total_stock=Sum('stock'))[
                    'total_stock'] or 0
        product_active = total > 0
        Product.objects.filter(id=self.product.id).update(total_stock=total, is_active=product_active)

    def __str__(self):
        return f"{self.product.title} - {self.color.title}  "

    def get_discounted_price(self):
        discount = (self.discount / 100) * int(self.price)
        return self.price - int(discount)

    def how_mutch_discounted(self):
        discount = (self.discount / 100) * int(self.price)
        return int(discount)


class ClothesPart(models.Model):
    name = models.CharField(max_length=100, verbose_name='قطعه لباس')

    class Meta:
        verbose_name = 'قطعه لباس'
        verbose_name_plural = 'قطعات لباس'

    def __str__(self):
        return self.name


class PartAttribute(models.Model):
    name = models.CharField(max_length=100, verbose_name='ویژگی اندازه‌گیری')

    class Meta:
        verbose_name = 'ویژگی اندازه‌گیری'
        verbose_name_plural = 'ویژگی‌های اندازه‌گیری'

    def __str__(self):
        return self.name


class MeasurementPreset(models.Model):
    clothing_part = models.ForeignKey(ClothesPart, on_delete=models.CASCADE, verbose_name='قطعه لباس')
    size = models.ForeignKey(Size, on_delete=models.CASCADE, verbose_name='سایز')

    class Meta:
        verbose_name = 'الگوی اندازه‌گیری'
        verbose_name_plural = 'الگوهای اندازه‌گیری'
        unique_together = ['clothing_part', 'size']

    def __str__(self):
        return f"{self.clothing_part} - {self.size}"


class MeasurementItem(models.Model):
    preset = models.ForeignKey(MeasurementPreset, on_delete=models.CASCADE, related_name='items',
                               verbose_name='الگوی اندازه‌گیری')
    attribute = models.ForeignKey(PartAttribute, on_delete=models.CASCADE, verbose_name='ویژگی')
    value = models.CharField(max_length=50, verbose_name='مقدار')

    class Meta:
        verbose_name = 'مقدار اندازه‌گیری'
        verbose_name_plural = 'مقادیر اندازه‌گیری'

    def __str__(self):
        return f"{self.preset} / {self.attribute}: {self.value}"


class ProductMeasurement(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='measurements', verbose_name='محصول')

products/templates/products/categories.html
{% extends 'base/index.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link rel="stylesheet" href="{% static 'css/categories.css' %}">
{% endblock %}
{% block title %}
    دسته‌بندی ها | فروشگاه آتوسا
{% endblock %}

{% block description %}
    همه دسته‌بندی‌های لباس با کیفیت بالا و قیمت مناسب را در فروشگاه آتوسا ببینید. شامل لباس دخترانه، پسرانه، تابستانی،
    زمستانی و ...
{% endblock %}
{% block og_title %}دسته‌بندی لباس کودک | فروشگاه آتوسا{% endblock %}
{% block og_description %}همه دسته‌های لباس کودک در فروشگاه آتوسا با طراحی شیک و قیمت مناسب. ارسال سریع به سراسر
    ایران.{% endblock %}
{% block og_image %}{% static 'image/fav/android-chrome-512x512.png' %}{% endblock %}
{% block content %}
    <div id="categories-t">
        <h1>دسته بندی ها</h1>
    </div>
    <div>{% include 'products/partials/_cat_partial.html' with categorya=categorya %}</div>

{% endblock %}

products/templates/products/products_list.html
{% extends 'base/index.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href={% static "css/product_list.css" %}>{% endblock %}
{% block meta %}
    {% if request.GET.page or request.GET.ordering or request.GET.color or request.GET.size or request.GET.price %}
        <link rel="canonical" href="{{ request.path }}">
    {% else %}
        <link rel="canonical" href="{{ request.build_absolute_uri }}">
    {% endif %}
{% endblock %}
{% block title %}لیست محصولات{% endblock %}
{% block content %}
    <div class="container">
        <div class="mobile-top-bar mobile" id="mobile-filter-bar">
            <button onclick="openDrawer('filters')">
                <img src="/static/image/icons/filter.svg" alt=""> فیلترها
            </button>
            <button onclick="openDrawer('sort')">
                <img src="/static/image/icons/order-by.svg" alt=""> مرتب‌سازی
            </button>
        </div>
        <!-- پرده تارکننده -->
        <div class="overlay mobile" id="overlay" onclick="closeDrawer()"></div>

        <!-- پنل فیلترها -->
        <div class="drawer drawer-full mobile" id="drawer-filters">
            <form id="filter-form-mobile" method="get" action="">
                <div class="drawer-header">
                    <div style="display:flex; align-items:center; gap:10px;">
                        <button id="backBtn" aria-label="بازگشت" type="button">
                            <img src="/static/image/icons/back.svg" alt="بازگشت">
                        </button>
                        <p id="drawerTitle">فیلترها</p>
                    </div>
                    <button class="close-btn" onclick="closeDrawer()" aria-label="بستن" type="button">X</button>
                </div>

                <div class="drawer-body mobile">
                    <div id="filter-main">
                        <button type="button" class="filter-btn" data-filter="دسته بندی‌ها">
                            دسته بندی‌ها
                            <img src="/static/image/icons/forward.svg" alt="›">
                        </button>
                        <button type="button" class="filter-btn" data-filter="رنگ‌ها">
                            رنگ‌ها
                            <img src="/static/image/icons/forward.svg" alt="›">
                        </button>
                        <button type="button" class="filter-btn" data-filter="جنسیت">
                            جنسیت
                            <img src="/static/image/icons/forward.svg" alt="›">
                        </button>
                        <button type="button" class="filter-btn" data-filter="قیمت">
                            قیمت
                            <img src="/static/image/icons/forward.svg" alt="›">
                        </button>
                        <button type="button" class="filter-btn" data-filter="سایز">
                            سایز
                            <img src="/static/image/icons/forward.svg" alt="›">
                        </button>
                    </div>

                    <div id="filter-detail" class="mobile" style="display:none;">
                        <div class="filter-content" id="filter-category" style="display:none;">
                            {% include "home/includes/header_categories.html" %}
                        </div>

                        <div class="filter-content mobile" id="filter-color" style="display:none;">
                            <div id="color-filter">
                                {% for color in colors %}
                                    <div id="color-wrapper">
                                        <div>{{ color.title }}</div>
                                        <div class="option-item" data-value="{{ color.id }}"
                                             style="background-color: {{ color.hex_color }};">
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                            <input type="hidden" name="color" id="colorInputMobile" value="">
                        </div>
                        <div class="filter-content" id="filter-gender" style="display:none;">
                            <div id="gender-buttons">
                                <button class="gender-btn boy" type="button" onclick="selectGenderMobile('boys')">پسرانه
                                </button>
                                <button class="gender-btn girl" type="button" onclick="selectGenderMobile('girls')">
                                    دخترانه
                                </button>
                            </div>
                            <input type="hidden" name="gender" id="genderInputMobile" value="">
                        </div>
                        <div class="filter-content" id="filter-price" style="display:none;">
                            <div class="price-filter">
                                <div class="range-slider">
                                    <input type="range" id="price_min_mobile" name="price__gt" min="0"
                                           max="{{ price_max }}" step="10000" value="{{ price_min }}"
                                           class="filter-input-range">
                                    <input type="range" id="price_max_mobile" name="price__lt" min="0"
                                           max="{{ price_max }}" step="10000" value="{{ price_max }}"
                                           class="filter-input-range">
                                </div>
                                <div class="price-values">
                                    <span>از: <span id="price_min_val_mobile">{{ price_min }}</span> تومان</span>
                                    <span>تا: <span id="price_max_val_mobile">{{ price_max }}</span> تومان</span>
                                </div>
                            </div>
                        </div>
                        <div class="filter-content" id="filter-size" style="display:none;">
                            <div id="size-filter">

                                {% for size in sizes %}
                                    <p>
                                        {{ size.age_min }} تا {{ size.age_max }}
                                        <input class="checkbox-size-mobile" type="checkbox" name="size"
                                               value="{{ size.title }}">
                                    </p>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>

                <div class="drawer-footer mobile">
                    <button id="clear-filters-mobile" type="button">لغو فیلترها</button>
                    <button class="apply-btn" type="button">اعمال فیلتر</button>
                </div>
            </form>
        </div>

        <!-- پنل مرتب‌سازی -->
        <div class="drawer drawer-half mobile" id="drawer-sort">
            <div class="drawer-header">
                <p> مرتب ‌سازی بر اساس</p>
                <button class="close-btn" onclick="closeDrawer()">X</button>
            </div>
            <div class="drawer-body">
                <button class="sort-btn" data-ordering="-views">محبوب ‌ترین</button>
                <button class="sort-btn" data-ordering="-created_at">جدید ترین</button>
                <button class="sort-btn" data-ordering="price">ارزان ‌ترین</button>
                <button class="sort-btn" data-ordering="-price">گران ‌ترین</button>
                <button class="sort-btn" data-ordering="-discount">بیشترین تخفیف</button>
            </div>
        </div>
        <div class="sort-menu desktop">
            <div class="category-dropdown">
                <div class="dropdown-toggle">دسته‌بندی‌ها</div>
                <ul class="dropdown-menu">
                    {% include 'products/partials/_category_list.html' with categories=categories %}
                </ul>
            </div>
            <button class="sort-btn" data-ordering="-views">محبوب ‌ترین</button>
            <button class="sort-btn" data-ordering="-created_at">جدید ترین</button>
            <button class="sort-btn" data-ordering="price">ارزان ‌ترین</button>
            <button class="sort-btn" data-ordering="-price">گران ‌ترین</button>
            <button class="sort-btn" data-ordering="-discount">بیشترین تخفیف</button>
        </div>
        <div>

        </div>
        <input type="hidden" name="ordering" id="orderingInput">
        <div class="content-wrapper">
            <div class="filter-box desktop">
                <div id="filter-title"><h2>جستجوی پیشرفته</h2></div>
                <form id="filter-form">
                    <button id="clear-filters" type="button">لغو فیلترها</button>
                    <!-- رنگ -->
                    <div id="filter-title"><h3 id="label-filter">انتخاب رنگ</h3></div>
                    <div id="color-filter">
                        <div class="custom-select" id="colorSelect">
                            <div class="selected-option">همه</div>
                            <div class="options-list">
                                <div class="option-item" data-value="all">
                                    نمایش همه
                                </div>
                                {% for color in colors %}
                                    <div class="option-item" data-value="{{ color.id }}"
                                         style="background-color: {{ color.hex_color }};">
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                        <input type="hidden" name="color" id="colorInput">
                    </div>

                    <!-- جنسیت -->
                    <div class="filter-item">
                        <h3 id="label-filter">پوشاک</h3>
                        <div id="gender-buttons">
                            <button class="gender-btn" id="boy-btn" type="button" onclick="selectGender('boys')">
                                پسرانه
                            </button>
                            <button class="gender-btn" id="girl-btn" type="button" onclick="selectGender('girls')">
                                دخترانه
                            </button>
                        </div>
                    </div>

                    <input type="hidden" name="gender" id="gender-input">

                    <!-- سایز -->
                    <div id="filter-title"><h3 id="label-filter">سایز</h3></div>
                    <div id="size-filter">

                        {% for size in sizes %}
                            <p>
                                <input type="checkbox" name="size" value="{{ size.title }}" onchange="triggerFilter()">
                                {{ size.age_min }} تا {{ size.age_max }}
                            </p>
                        {% endfor %}
                    </div>


                    <!-- قیمت -->
                    <div id="filter-title"><h3 id="label-filter">فیلتر قیمت</h3></div>
                    <div class="price-filter">
                        <div class="range-slider">
                            <input type="range" id="price_min" name="price__gt" min="0" max="{{ price_max }}"
                                   step="10000"
                                   value="{{ price_min }}"
                                   class="filter-input-range">
                            <input type="range" id="price_max" name="price__lt" min="0" max="{{ price_max }}"
                                   step="10000"
                                   value="{{ price_max }}" class="filter-input-range">
                        </div>
                        <div class="price-values">
                            <span>از: <span id="price_min_val">{{ price_min }}</span> تومان</span>
                            <span>تا: <span id="price_max_val">{{ price_max }}</span> تومان</span>
                        </div>
                    </div>
                </form>
            </div>

            <div id="product-list" class="product-grid">
                {% include 'products/partials/_product_list.html' %}
            </div>

        </div>
    </div>
{% endblock %}

{% block js %}
    <script src={% static "js/filter.js" %}></script>{% endblock %}